# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run:

    runs-on: ubuntu-latest

    env:
      GithubApiToken: ${{secrets.GH_API_TOKEN}}
      GithubUser: Mahdi0024
      GithubRepo: ProxyCollector
      Timeout: 5000
      Retries: 5
      MaxThreadCount: 24
      ResultFilePath: sub/proxies.txt
      IpInfoApiToken: ${{secrets.IPINFOAPITOKEN}}
      SingboxPath: sing-box
      Sources: ${{secrets.SOURCES}}
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.4.3/sing-box_1.4.3_linux_amd64.deb
        sudo dpkg -i sing-box_1.4.3_linux_amd64.deb
        sudo apt-get install -f
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Run
      run: dotnet run --configuration Release --project ProxyCollector
