# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run ProxyCollector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  run:

    runs-on: ubuntu-latest

    env:
      GithubApiToken: ${{secrets.GH_API_TOKEN}}
      GithubUser: Mahdi0024
      GithubRepo: ProxyCollector
      Timeout: 7000
      MaxThreadCount: 96
      SingboxPath: sing-box
      V2rayFormatResultPath: sub/proxies.txt
      SingboxFormatResultPath: sub/singbox.txt
      Sources: |
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription2
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription3
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription4
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription5
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription6
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription7
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription8
        https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
        https://raw.githubusercontent.com/freefq/free/master/v2
        https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
        https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt
        https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
        https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
        https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/normal/mix
        https://raw.githubusercontent.com/freev2rayconfig/V2RAY_SUB/main/v2ray.txt
        https://api.yebekhe.link/shervin/
        https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/mixed
        https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_Sub.txt
        https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/mix.txt
        https://raw.githubusercontent.com/a2470982985/getNode/main/v2ray.txt
        https://raw.githubusercontent.com/sashalsk/V2Ray/main/V2Config
        https://raw.githubusercontent.com/sashalsk/V2Ray/main/V2Ray-list-current
        https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/mixed
        https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/merged.txt
        https://nodefree.org/dy/2024/02/20240228.txt
        https://clashnode.com/wp-content/uploads/2024/02/20240228.txt
        https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
        https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt
        https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
        https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/free
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.6.4/sing-box_1.6.4_linux_amd64v3.deb
        sudo dpkg -i sing-box_1.6.4_linux_amd64v3.deb
        sudo apt-get install -f
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Run
      run: dotnet run --configuration Release --project ProxyCollector
