# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run ProxyCollector

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  run:

    runs-on: ubuntu-latest

    env:
      GithubApiToken: ${{secrets.GH_API_TOKEN}}
      IpInfoApiToken: ${{secrets.IPINFOAPITOKEN}}
      GithubUser: Mahdi0024
      GithubRepo: ProxyCollector
      Timeout: 5000
      Retries: 5
      MaxThreadCount: 16
      SingboxPath: sing-box
      ResultFilePath: sub/proxies.txt
      Sources: |
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription2
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription3
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription4
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription5
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription6
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription7
        https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription8
        https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
        https://raw.githubusercontent.com/freefq/free/master/v2
        https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
        https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt
        https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
        https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
        https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/mix
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.4.3/sing-box_1.4.3_linux_amd64.deb
        sudo dpkg -i sing-box_1.4.3_linux_amd64.deb
        sudo apt-get install -f
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Run
      run: dotnet run --configuration Release --project ProxyCollector
