# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GithubApiToken: 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
      GithubUser: Mahdi0024
      GithubRepo: ProxyCollector
      Timeout: 3000
      Retries: 4
      MaxThreadCount: 16
      ResultFilePath: sub/results.txt
      IpInfoApiToken: 4726787b276af2
      SingboxPath: sing-box
      Sources: https://proxy.yugogo.xyz/vmess/sub,https://proxy.yugogo.xyz/trojan/sub,https://proxy.yugogo.xyz/sip002/sub,https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription2,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription3,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription4,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription5,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription6,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription7,https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription8,https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/splitted/vmess.txt,https://raw.githubusercontent.com/freefq/free/master/v2,https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.txt,https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray,https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt,https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2,https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub,https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/mix,https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/donated,https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.4.3/sing-box_1.4.3_linux_amd64.deb
        sudo dpkg -i sing-box_1.4.3_linux_amd64.deb
        sudo apt-get install -f
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run
      run: dotnet Run --configuration Release
